repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.13.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]
  - repo: https://github.com/psf/black
    # black config is in pyproject.toml
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
        exclude: ^docs
  - repo: https://github.com/timothycrosley/isort
    # isort config in pyproject.toml does not work FIXME
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3
        args: [--profile=black, --line-length=120]
  - repo: https://github.com/PyCQA/flake8
    # flake8 config is in .flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3
        exclude: ^docs
  - repo: https://github.com/rtts/djhtml
    rev: "3.0.6"  # replace with the latest tag on GitHub
    hooks:
      - id: djhtml
        args: [-t, "2"]
