# Config file for automatic testing at travis-ci.org

language: python
dist: buster

python:
  - "3.8"

env:
  - TOX_ENV=py38-django-30

before_install:
  - pip install poetry

install:
  - poetry install

matrix:
  fast_finish: true

# command to run tests using coverage, e.g. python setup.py test
script:
  - poetry run coverage run --source src/wagtail_srcset/templatetags --branch runtests.py tests 

after_success:
  - codecov -e TOX_ENV
